!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.21.2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_math_lib_gamma (gammaf2pywrap, x)
      use math_lib, only : gamma
      real(kind=8) x
      real(kind=8) gammaf2pywrap
      gammaf2pywrap = gamma(x)
      end subroutine f2pywrap_math_lib_gamma
      subroutine f2pywrap_math_lib_path_integral (path_integralf2pywrap,&
     & f, s, i1, i2, f2py_f_d0, f2py_s_d0)
      use math_lib, only : path_integral
                use m_mrgrnk, only: mrgrnk
                use array_lib
      integer(kind=4) i1
      integer(kind=4) i2
      integer f2py_f_d0
      integer f2py_s_d0
      real(kind=8) f(f2py_f_d0)
      real(kind=8) s(f2py_s_d0)
      real(kind=8) path_integralf2pywrap
      path_integralf2pywrap = path_integral(f, s, i1, i2)
      end subroutine f2pywrap_math_lib_path_integral
      subroutine f2pywrap_math_lib_vals_equal (vals_equalf2pywrap, val1,&
     & val2)
      use math_lib, only : vals_equal
      real(kind=8) val1
      integer val2
      logical vals_equalf2pywrap
      vals_equalf2pywrap = .not.(.not.vals_equal(val1, val2))
      end subroutine f2pywrap_math_lib_vals_equal
      subroutine f2pywrap_math_lib_vals_differ (vals_differf2pywrap, val&
     &1, val2)
      use math_lib, only : vals_differ
      real(kind=8) val1
      integer val2
      logical vals_differf2pywrap
      vals_differf2pywrap = .not.(.not.vals_differ(val1, val2))
      end subroutine f2pywrap_math_lib_vals_differ
      
      subroutine f2pyinitmath_lib(f2pysetupfunc)
      use math_lib, only : avint
      interface 
      subroutine f2pywrap_math_lib_gamma (gammaf2pywrap, gamma, x)
      real(kind=8) gamma
      real(kind=8) x
      real(kind=8) gammaf2pywrap
      end subroutine f2pywrap_math_lib_gamma 
      subroutine f2pywrap_math_lib_path_integral (path_integralf2pywrap,&
     & path_integral, f, s, i1, i2, f2py_f_d0, f2py_s_d0)
      real(kind=8) path_integral
      integer(kind=4) i1
      integer(kind=4) i2
      integer f2py_f_d0
      integer f2py_s_d0
      real(kind=8) f(f2py_f_d0)
      real(kind=8) s(f2py_s_d0)
      real(kind=8) path_integralf2pywrap
      end subroutine f2pywrap_math_lib_path_integral 
      subroutine f2pywrap_math_lib_vals_equal (vals_equalf2pywrap, vals_&
     &equal, val1, val2)
      logical vals_equal
      real(kind=8) val1
      integer val2
      logical vals_equalf2pywrap
      end subroutine f2pywrap_math_lib_vals_equal 
      subroutine f2pywrap_math_lib_vals_differ (vals_differf2pywrap, val&
     &s_differ, val1, val2)
      logical vals_differ
      real(kind=8) val1
      integer val2
      logical vals_differf2pywrap
      end subroutine f2pywrap_math_lib_vals_differ
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_math_lib_gamma,f2pywrap_math_lib_path_&
     &integral,avint,f2pywrap_math_lib_vals_equal,f2pywrap_math_lib_vals&
     &_differ)
      end subroutine f2pyinitmath_lib


