C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.21.2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapgases (gasesf2pywrap, pres_mb, t, rh, f)
      external gases
      real*8 pres_mb
      real*8 t
      real*8 rh
      real*8 f
      real*8 gasesf2pywrap, gases
      gasesf2pywrap = gases(pres_mb, t, rh, f)
      end

